spring:
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    password: ${DB_USER:postgres}
    username: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always