apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      name: spring-boot-app
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: app
          image: reluckyyy/srefinal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: "300Mi"
            requests:
              cpu: "0.5"
              memory: "300Mi"
          env:
            - name: 'spring.datasource.url'
              value: jdbc:postgresql://postgres:5432/postgres
            - name: 'jakarta.persistence.jdbc.url'
              value: jdbc:postgresql://postgres:5432/postgres
            - name: 'elastic.url'
              value: 'host.docker.internal:9200'
            - name: 'LOGSTASH_HOST'
              value: 'host.docker.internal'
            - name: 'server.port'
              value: '8000'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  selector:
    app: spring-boot-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-boot-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-boot-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      command: ["/bin/sh", "-c"]
      args:
        - >
          while true; do
            wget -q -O- spring-boot-app-service:8000/api/v1/main/bye;
          done